name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "_AnimeZid.com_.The.Mitchells.vs.The.Machines.2021.NF.WEB-DL.1080.Dubbed.Ar.mp4"
  comment: "_AnimeZid.com_.The.Mitchells.vs.The.Machines.2021.NF.WEB-DL.1080.Dubbed.Ar.mp4"
  url: "https://doc-0c-3s-docs.googleusercontent.com/docs/securesc/rv7glar8hq5f1bg56o13p7u2o3lld76g/ep7bfl8uglckn2gp9q46260vo4b9bo4j/1636835400000/13703350687659623855/13703350687659623855/1FCY2HvAhx97o2k5rM1z9Wlo7iZSelPGI?e=download&authuser=0&nonce=as1r0l9gl4fhu&user=13703350687659623855&hash=3t5npti4s766eu1e5erklok32thujjh3"
  file_name: "_AnimeZid.com_.The.Mitchells.vs.The.Machines.2021.NF.WEB-DL.1080.Dubbed.Ar.mp4"
  piece_size: 19 # Check the README.md for recommended piece size
  maximize_disk_space: false # Set to true if out of disk space
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        if: ${{ env.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: aria2c -x 16 -o "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name" # Tested on v1.1
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
