name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "UP0082-CUSA10938_00-SHADOWTOMBRAIDER-A0201-V0101_1.pkg"
  comment: "UP0082-CUSA10938_00-SHADOWTOMBRAIDER-A0201-V0101_1.pkg"
  url: "http://gs2.ww.prod.dl.playstation.net/gs2/ppkgo/prod/CUSA10938_00/24/f_f876c05bfb7dcca267c25e6e05734241e71fa0e73883cb02d76824004b6542fe/f/UP0082-CUSA10938_00-SHADOWTOMBRAIDER-A0201-V0101_1.pkg"
  file_name: "UP0082-CUSA10938_00-SHADOWTOMBRAIDER-A0201-V0101_1.pkg"
  piece_size: 19 # Check the README.md for recommended piece size
  maximize_disk_space: false # Set to true if out of disk space
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        if: ${{ env.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: aria2c -x 16 -o "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name" # Tested on v1.1
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
