name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "UP4008-CUSA23446_00-TWT2SIEA00000000-A0113-V0100_1.pkg"
  comment: "UP4008-CUSA23446_00-TWT2SIEA00000000-A0113-V0100_1.pkg"
  url: "http://gs2.ww.prod.dl.playstation.net/gs2/ppkgo/prod/CUSA23446_00/15/f_a6c82cbd394e3cbfbc5096ef3c02ef194acab5bc9c92962339baaa102fe66139/f/UP4008-CUSA23446_00-TWT2SIEA00000000-A0113-V0100_1.pkg"
  file_name: "UP4008-CUSA23446_00-TWT2SIEA00000000-A0113-V0100_1.pkg"
  piece_size: 19 # Check the README.md for recommended piece size
  maximize_disk_space: false # Set to true if out of disk space
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        if: ${{ env.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: aria2c -x 16 -o "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name" # Tested on v1.1
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
