name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "UP0006-CUSA08724_00-BATTLEFIELDV0000-A0138-V0100_5.pkg"
  comment: "UP0006-CUSA08724_00-BATTLEFIELDV0000-A0138-V0100_5.pkg"
  url: "http://gs2.ww.prod.dl.playstation.net/gs2/ppkgo/prod/CUSA08724_00/44/f_b33e429644fac27b7638dee1d00d851f5a09c2a8e920da8e0e9ae5b1491b153f/f/UP0006-CUSA08724_00-BATTLEFIELDV0000-A0138-V0100_5.pkg"
  file_name: "UP0006-CUSA08724_00-BATTLEFIELDV0000-A0138-V0100_5.pkg"
  piece_size: 19 # Check the README.md for recommended piece size
  maximize_disk_space: false # Set to true if out of disk space
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        if: ${{ env.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: aria2c -x 16 -o "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name" # Tested on v1.1
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
