name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "file1"
  comment: "[AnimeZid.com].Despicable.Me.3.2017.BluRay.1080.Dubbed.Ar.mp4"
  url: "https://www61.uptobox.com/dl/67-kQt_OF-jVVx79of_lLEjSLnTl4jN4GSzbMEqTVL5ciCDAc6E8k8BbBjIqwOJ6y4FBrR-M-voKnwEATAbDW1KtRYlj1xzKTPFd1m-onV6357yyHz5fdiMnBM--KymyXl6M4tJiJ6A89e4a-xx-sg/%5BAnimeZid.com%5D.Despicable.Me.3.2017.BluRay.1080.Dubbed.Ar.mp4"
  file_name: "[AnimeZid.com].Despicable.Me.3.2017.BluRay.1080.Dubbed.Ar.mp4"
  piece_size: 19 # Check the README.md for recommended piece size
  maximize_disk_space: false # Set to true if out of disk space
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        if: ${{ env.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: aria2c -x 16 -o "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name" # Tested on v1.1
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
