name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "UP9000-CUSA08966_00-DAYSGONECOMPLETE-A0170-V0100_2.pkg"
  comment: "UP9000-CUSA08966_00-DAYSGONECOMPLETE-A0170-V0100_2.pkg"
  url: "http://gs2.ww.prod.dl.playstation.net/gs2/ppkgo/prod/CUSA08966_00/38/f_75cf96ba0907731b5338b040a4122b64f3cf4be5c6def5b2b55eee8c4d971a39/f/UP9000-CUSA08966_00-DAYSGONECOMPLETE-A0170-V0100_2.pkg"
  file_name: "UP9000-CUSA08966_00-DAYSGONECOMPLETE-A0170-V0100_2.pkg"
  piece_size: 19 # Check the README.md for recommended piece size
  maximize_disk_space: false # Set to true if out of disk space
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        if: ${{ env.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: aria2c -x 16 -o "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name" # Tested on v1.1
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
