name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "Mickey_.Donald_.Goofy.the.Three.Musketeers.2004.WEB-DL.1080.Dubbed.Ar_SamaUp.mp4"
  comment: "Mickey_.Donald_.Goofy.the.Three.Musketeers.2004.WEB-DL.1080.Dubbed.Ar_SamaUp.mp4"
  url: "https://fs2.cdnrobot.xyz/2k43A/Mickey,.Donald,.Goofy.the.Three.Musketeers.2004.WEB-DL.1080.Dubbed.Ar.mp4?download_token=8ecd48aabfb04f5712d25a515b08eb0d6dd462107abaad00bd8e9ebabfe42a6f"
  file_name: "Mickey_.Donald_.Goofy.the.Three.Musketeers.2004.WEB-DL.1080.Dubbed.Ar_SamaUp.mp4"
  piece_size: 19 # Check the README.md for recommended piece size
  maximize_disk_space: false # Set to true if out of disk space
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        if: ${{ env.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: aria2c -x 16 -o "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name" # Tested on v1.1
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
