name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "EP1004-CUSA00411_00-GTAVDIGITALDOWNL-A0137-V0100_0.pkg"
  comment: "EP1004-CUSA00411_00-GTAVDIGITALDOWNL-A0137-V0100_0.pkg"
  url: "http://gs2.ww.prod.dl.playstation.net/gs2/ppkgo/prod/CUSA00411_00/51/f_12f094c61af342ee15569084095b735887a7179e3ef6016450ef5079591ad2cb/f/EP1004-CUSA00411_00-GTAVDIGITALDOWNL-A0137-V0100_0.pkg"
  file_name: "EP1004-CUSA00411_00-GTAVDIGITALDOWNL-A0137-V0100_0.pkg"
  piece_size: 19 # Check the README.md for recommended piece size
  maximize_disk_space: false # Set to true if out of disk space
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        if: ${{ env.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: aria2c -x 16 -o "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name" # Tested on v1.1
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
