name: Create torrent using py3createtorrent
on:
  push:
    branches:
      - master 

env:
  url_1: "http://gs2.ww.prod.dl.playstation.net/gs2/appkgo/prod/CUSA01073_00/2/f_124587cd15d63dda9395a6ff2c5ea26145a2a095cad75d458b05783e3c1f56c0/f/EP9000-CUSA01073_00-RCPS400000000000_4.pkg"
  file_name_1: "EP9000-CUSA01073_00-RCPS400000000000_4.pkg"
  
  
  url_2: "http://gs2.ww.prod.dl.playstation.net/gs2/appkgo/prod/CUSA01073_00/2/f_124587cd15d63dda9395a6ff2c5ea26145a2a095cad75d458b05783e3c1f56c0/f/EP9000-CUSA01073_00-RCPS400000000000_5.pkg"
  file_name_2: "EP9000-CUSA01073_00-RCPS400000000000_5.pkg"
  
 
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file 1
        run: wget -nv -O "$file_name_1" "$url_1"
                
      - name: Download file 2
        run: wget -nv -O "$file_name_2" "$url_2"
         
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '0 day'
         
      - name: Upload torrent file 1
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.file_name_1 }}
          path: ${{ env.file_name_1 }}
          
      - name: Upload torrent file 2
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.file_name_2 }}
          path: ${{ env.file_name_2 }}
   
