name: Create torrent using transmission
on:
  push:
    paths:
      - ".github/workflows/Testme.yml"
      
env:
  name: "Z55%201903.iso"
  comment: "Z55%201903.iso"
  url: "https://p-lux4.pcloud.com/cBZX7B1oWZgUHxNnZZZAPjrc7Z2ZZp9LZkZnsoT4JZVRZdHZSLZyLZiRZEzZDLZeLZPRZHLZR4ZW4ZzHZnRZ9H4bXZvPlJV5KYIGhC93kQGBJAw0NqAdDX/Z55%201903.iso"
  file_name: "Z55%201903.iso"
  piece_size: 19 # Check the README.md for recommended piece size
  maximize_disk_space: false # Set to true if out of disk space
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        if: ${{ env.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v7
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install transmission
        run: sudo apt install transmission-cli
        
      - name: Download torrent
        run: transmission-cli magnet:?xt=urn:btih:af2a6c731512ba28aced24b2e738bfb37989c2a9&dn=Aladdin%20(1992)&xl=8242709495&tr=http://www.arabp2p.net:2052/e6d79d94f251e59fe472897d0d98c5d3/announce -w ~/Downloads
        

