name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/test.yml"

env:
  url_1: "http://gs2.ww.prod.dl.playstation.net/gs2/appkgo/prod/CUSA07211_00/6/f_4d086b5fafc3f1de8a43dab5829bb61d97436e5d685236bb3d43e0edbd98178c/f/UP0082-CUSA07211_00-FFVIIREMAKE00000_16.pkg"
  file_name_1: "UP0082-CUSA07211_00-FFVIIREMAKE00000_14.pkg"
  
  url_2: "http://gs2.ww.prod.dl.playstation.net/gs2/appkgo/prod/CUSA07211_00/6/f_4d086b5fafc3f1de8a43dab5829bb61d97436e5d685236bb3d43e0edbd98178c/f/UP0082-CUSA07211_00-FFVIIREMAKE00000_17.pkg"
  file_name_2: "UP0082-CUSA07211_00-FFVIIREMAKE00000_15.pkg"
  
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file 1
        run: wget -nv -O "$file_name_1" "$url_1"
                
      - name: Download file 2
        run: wget -nv -O "$file_name_2" "$url_2"

        
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '0 day'
         
      - name: Upload torrent file 1
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.file_name_1 }}
          path: ${{ env.file_name_1 }}
          
      - name: Upload torrent file 2
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.file_name_2 }}
          path: ${{ env.file_name_2 }}
