name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/test.yml"

env:
  url_1: "http://gs2.ww.prod.dl.playstation.net/gs2/appkgo/prod/CUSA00133_00/8/f_73f96a3a328210f66ab69e6d9e66484b19f4fce07cbdbe0a34dee50d8dc1039f/f/UP1018-CUSA00133_00-BATMANARKHAMKNHT_0.pkg"
  file_name_1: "UP1018-CUSA00133_00-BATMANARKHAMKNHT_0.pkg"
  
  url_2: "http://gs2.ww.prod.dl.playstation.net/gs2/appkgo/prod/CUSA00133_00/8/f_73f96a3a328210f66ab69e6d9e66484b19f4fce07cbdbe0a34dee50d8dc1039f/f/UP1018-CUSA00133_00-BATMANARKHAMKNHT_5.pkg"
  file_name_2: "UP1018-CUSA00133_00-BATMANARKHAMKNHT_5.pkg"
  
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file 1
        run: wget -nv -O "$file_name_1" "$url_1"
                
      - name: Download file 2
        run: wget -nv -O "$file_name_2" "$url_2"

        
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '0 day'
         
      - name: Upload torrent file 1
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.file_name_1 }}
          path: ${{ env.file_name_1 }}
          
      - name: Upload torrent file 2
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.file_name_2 }}
          path: ${{ env.file_name_2 }}
