name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/test.yml"

env:
  url_1: "http://gs2.ww.prod.dl.playstation.net/gs2/appkgo/prod/CUSA08469_00/3/f_09edc9e9d3f950b346586c7dbc46adb2fb1aeafd504c931468a34061f2c0181a/f/UP1018-CUSA08469_00-LEGOMARVELSH2001_3.pkg"
  file_name_1: "UP1018-CUSA08469_00-LEGOMARVELSH2001_3.pkg"
  
  url_2: "http://gs2.ww.prod.dl.playstation.net/gs2/appkgo/prod/CUSA08469_00/3/f_09edc9e9d3f950b346586c7dbc46adb2fb1aeafd504c931468a34061f2c0181a/f/UP1018-CUSA08469_00-LEGOMARVELSH2001_4.pkg"
  file_name_2: "UP1018-CUSA08469_00-LEGOMARVELSH2001_4.pkg"
  
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file 1
        run: wget -nv -O "$file_name_1" "$url_1"
                
      - name: Download file 2
        run: wget -nv -O "$file_name_2" "$url_2"

        
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '0 day'
         
      - name: Upload torrent file 1
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.file_name_1 }}
          path: ${{ env.file_name_1 }}
          
      - name: Upload torrent file 2
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.file_name_2 }}
          path: ${{ env.file_name_2 }}
